Compare with major release version
puppetlabs/puppetlabs-apache pull request #2110
Opened 2020-12-22 18:16 UTC by ekohl

CentOS 8 stream doesn't have a minor version so this check likely fails. However, it's irrelevant here and we can use the major release version fact instead.

There are a lot more odd cases with facts, but I don't want to touch too much code.

2021-01-04 12:11 UTC, sanfrancrisko requested changes
Thanks for the tweak @ekohl - it appears as though we have test failures on Travis due to the `versioncmp` being passed an undefined variable: https://travis-ci.com/github/puppetlabs/puppetlabs-apache/jobs/464049567

2021-01-04 12:13 UTC, ekohl commented
That's probably because the module doesn't use rspec-puppet-facts but rather specifies them manually. I had a look at the module, but its test infra is in serious need of an update.

2021-01-18 11:06 UTC, sanfrancrisko commented
> That's probably because the module doesn't use rspec-puppet-facts but rather specifies them manually. I had a look at the module, but its test infra is in serious need of an update.

Agreed - it would make things a lot nicer to use `rspec-puppet-facts` consistently across the module. I took a look at `spec/classes/apache_spec.rb` and frankly, it's going to be quite a while to fix that one test class up - it's not going to be as simple as encapsulating the tests within a `on_supported_os.each` block (_not that I ever thought it would!_). There's a heck of a lot of duplication and specific tests coupled to specific OSs. I haven't even looked in to the other test classes failing either - I suspect a similar scenario awaits in them.

I'm not saying that it isn't the right thing to do, but, it would be quite an undertaking and a bit more surgical than a bulk edit. I'll discuss with some of the team on how we want to proceed. If you have any suggestions, we'd be keen to hear, of course 👍

2021-01-18 11:38 UTC, ekohl commented
I added another commit I wrote while looking into this. I think the main pain point comes from remaining compatible with Facter 1.6 for too long. https://github.com/puppetlabs/puppetlabs-stdlib/pull/1154 is another thing that should have died long ago with Facter 1.6.

About the conversion to rspec-puppet-facts. I think you're right that this won't be a trivial conversion. Another thing to note is that the test runtime will go up a lot since it'll test a lot more combinations. Perhaps a decent compromise is to define a default test OS in some shared file and use that instead of defining the same facts over and over again.

2021-02-06 23:30 UTC, ekohl commented
In https://github.com/puppetlabs/puppetlabs-apache/pull/2120 I took a stab at a the preparation. Not a full conversion to rspec-puppet-facts, but by using shared examples a big step forward is taken to make it easier.

2021-02-08 10:27 UTC, ekohl commented
This now includes https://github.com/puppetlabs/puppetlabs-apache/pull/2120 since hopefully that's sufficient to make the tests pass. Once that's merged, I'll rebase for easier review.

2021-02-15 12:47 UTC, ekohl commented
Rebased and squashed into a single commit. Also updated some fact sets to provide a major version.

2021-02-24 16:59 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-apache?pullRequest=2110) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-apache?pullRequest=2110) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-apache?pullRequest=2110) it.</sub>

2021-03-15 12:36 UTC, sanfrancrisko approved these changes

2021-03-15 13:51 UTC, david22swan approved these changes
LGTM

2021-03-15 13:51 UTC, david22swan commented
@ekohl Thanks for the excellent work as always
Looking forward to more in the future.

2021-03-15 13:51 UTC, merged