(FIX) Correct PHP packages on Ubuntu 16.04
puppetlabs/puppetlabs-apache pull request #2111
Opened 2021-01-05 16:26 UTC by ekohl

This corrects some module packages for Ubuntu 16.04. suphp was actually removed. The other packages are transitional packages. Using the modern ones aligns them with newer versions. It also greatly simplifies the params code.

2021-01-11 11:56 UTC, sanfrancrisko requested changes
One issue spotted. I'm also trying to get a https://github.com/puppetlabs/puppetlabs-apache/pull/2114 across the line to resolve the syntax check failures being caused at the moment. Some issues with that PR, but once it's merged, you can rebase and it should hopefully get your tests passing 🤞

2021-01-11 13:07 UTC, ekohl commented on manifests/params.pp
> +        '9', '16.04' => '7.0', # Debian Stretch, Ubuntu Xenial
I ended up with just adding another line.

2021-01-11 13:55 UTC, ekohl commented
RHEL 7 acceptance test failed with some internal server error so I'm guessing that's unrelated.

2021-01-11 14:48 UTC, sanfrancrisko commented
> RHEL 7 acceptance test failed with some internal server error so I'm guessing that's unrelated.

Yeah, I doubt it's related to your change - I'll keep an eye on it on this 2nd run after the rebase 🤞

2021-01-18 11:11 UTC, sanfrancrisko approved these changes
Thanks for the fix @ekohl !

2021-01-18 11:11 UTC, merged