Allow custom userdir directives
puppetlabs/puppetlabs-apache pull request #2164
Opened 2021-07-01 18:15 UTC by hunner

`UserDir` can be various forms of strings (see
https://httpd.apache.org/docs/2.4/howto/public_html.html) whereas
`Directory` must be an absolute path. This allows UserDir to be
specified separately.

The unit test showing multiple values for `$path` seems to be incorrect
according to https://httpd.apache.org/docs/2.4/mod/core.html#directory

2021-07-02 09:41 UTC, ekohl requested changes

2021-07-02 09:41 UTC, ekohl commented on manifests/mod/userdir.pp
> +  }
I'm always a fan of `pick`
```suggestion
  $_userdir = pick($userdir, $_path)
```

2021-07-02 09:41 UTC, ekohl commented on manifests/mod/userdir.pp
> +  $userdir = undef,
Can we add a data type for this? Is it `Optional[Stdlib::Absolutepath]` or `Optional[String[1]]`?

2021-07-02 09:41 UTC, ekohl commented on REFERENCE.md
> +Default value: The value of `$path`
This looks manually written since it doesn't match what's in the `@param`. You can generate it using `rake strings:generate:reference`

2021-07-20 19:01 UTC, ekohl approved these changes

2021-07-20 19:02 UTC, ekohl commented
Perhaps another reviewer can also take a look (I only got merge permissions recently). If nobody takes a look in a few days I'll merge it.

2021-07-26 12:27 UTC, david22swan approved these changes
LGTM

2021-07-26 12:28 UTC, david22swan commented
Look's good to me so gonna go ahead and merge :)

2021-07-26 12:28 UTC, merged