Added in basic auth and no-negotiate options
puppetlabs/puppetlabs-apache pull request #2204
Opened 2021-10-14 20:01 UTC by btoneill

Two big options for GSSAPI were not in the module, added them in.

2022-04-27 10:21 UTC, LukasAud commented
Hi @raybellis, sorry for the delay in feedback. We will be moving this back to active PRs and, hopefully, someone on our team can look at this soon. 

Meanwhile, as per @david22swan request, could you give us a bit more context on this change? What behaviour are these options responsible for? Are these common options or something more on the specialised area of apache? Any information you can provide will help us make a decision faster. Thank you for your patience.

2022-05-05 15:01 UTC, raybellis commented
These options (except for the two `Auth*` ones are likely to be wanted by anyone using Kerberos via Basic Authentication (as opposed to requiring that the client browser pass a Kerberos ticket via GSSAPI).

2022-05-10 14:48 UTC, david22swan requested changes
@btoneill Hey, sorry for the wait on review.

Anyway while the changes look good to me, aside from one small error I have noted, we would need some additional tests added in order to cover the new variables, the relevant test file being linked below:

- https://github.com/puppetlabs/puppetlabs-apache/blob/main/spec/defines/vhost_spec.rb

In addition while reviewing other apache PRs I found 3 others adding similar functionality to this one, one of which adds basicauth and has been merged in, i.e.:

- https://github.com/puppetlabs/puppetlabs-apache/pull/2212

Another that adds negotiate_once and has not yet been merged:

- https://github.com/puppetlabs/puppetlabs-apache/pull/2214

And a third that adds another 3 variables:

- https://github.com/puppetlabs/puppetlabs-apache/pull/2215

This is just a head's up so that you know to rebase your work and are aware that it may be fulfilled by another PR, depending on if it get's in a merge ready state before your own.

2022-05-10 14:48 UTC, david22swan commented on templates/vhost/_gssapi.epp
> +    GssapiNegotiateOnce <%= $basicauth %>
Small error, but should this not be:
```
GssapiNegotiateOnce <%= $negotiateonce %>
```

2022-06-08 15:24 UTC, david22swan commented
@btoneill Hey, sorry but gonna close this PR as another has been merged in that adds the same functionality:
https://github.com/puppetlabs/puppetlabs-apache/pull/2214
Thanks for putting in the work though and I hope to see more from you in the future.

2022-06-08 15:24 UTC, closed without merging