-Add support for all proxy schemes, not just https://
puppetlabs/puppetlabs-apache pull request #2289
Opened 2022-08-10 20:39 UTC by canth1

This commit fixes https://github.com/puppetlabs/puppetlabs-apache/issues/2285 by supporting all mod_proxy schemes according to the documentation here:

https://httpd.apache.org/docs/2.4/mod/mod_proxy.html

2022-08-12 10:22 UTC, ekohl commented
Looks like the tests fail on this.

I also wonder if this should be a defined type.

2022-08-15 09:06 UTC, david22swan commented
> Looks like the tests fail on this.
> 
> I also wonder if this should be a type alias.

I would agree on this

2022-08-15 09:07 UTC, david22swan requested changes
@canth1 
Hey, look's like you've got a few failing tests

Also, think that @ekohl suggestion is a good one and that this would be a good use of a type alias to keep the code neater

2022-08-17 09:49 UTC, ekohl approved these changes
Small detail, but this looks good.

2022-08-17 09:49 UTC, ekohl commented on types/modproxy.pp
> +type Apache::ModProxyProtocol = Pattern[/(\A(ajp|fcgi|ftp|h2|h2c|http|https|scgi|uwsgi|ws|wss):\/\/.*\z)/, /(\Aunix:\/([^\n\/\0]+\/*)*\z)/]
Is it valid to not specify anything or should it be
```suggestion
type Apache::ModProxyProtocol = Pattern[/(\A(ajp|fcgi|ftp|h2|h2c|http|https|scgi|uwsgi|ws|wss):\/\/.+\z)/, /(\Aunix:\/([^\n\/\0]+\/*)*\z)/]
```

2022-08-17 09:50 UTC, ekohl requested changes
Looks like the tests are failing.

Also, it's possible to add tests for a type alias: https://rspec-puppet.com/documentation/type_aliases/

2022-08-17 16:22 UTC, canth1 commented
> Small detail, but this looks good.

I don't think that's correct, because I took my regex directly from Stdlib:HTTPSUrl

https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/types/httpsurl.pp

Which is:

type Stdlib::HTTPSUrl = Pattern[/(?i:\Ahttps:\/\/.*\z)/]

2022-08-17 16:23 UTC, canth1 commented
> Looks like the tests are failing.
> 
> Also, it's possible to add tests for a type alias: https://rspec-puppet.com/documentation/type_aliases/

Ok, I'll add the tests for this new type alias.

2022-08-17 16:45 UTC, ekohl commented
> > Small detail, but this looks good.
> 
> I don't think that's correct, because I took my regex directly from Stdlib:HTTPSUrl
> 
> https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/types/httpsurl.pp
> 
> Which is:
> 
> type Stdlib::HTTPSUrl = Pattern[/(?i:\Ahttps://.*\z)/]

Interesting. That implies it also accepts `https://` which doesn't make sense to me since I don't consider it an HTTP(S) URL.

2022-08-17 16:50 UTC, ekohl commented on types/modproxy.pp
> +type Apache::ModProxyProtocol = Pattern[/(\A(ajp|fcgi|ftp|h2c?|https?|scgi|uwsgi|wss?):\/\/.*\z)/, /(\Aunix:\/([^\n\/\0]+\/*)*\z)/]
I don't think this is correct. The filename must match the type name.

2022-08-17 16:51 UTC, canth1 commented
> > > Small detail, but this looks good.
> > 
> > 
> > I don't think that's correct, because I took my regex directly from Stdlib:HTTPSUrl
> > https://github.com/puppetlabs/puppetlabs-stdlib/blob/main/types/httpsurl.pp
> > Which is:
> > type Stdlib::HTTPSUrl = Pattern[/(?i:\Ahttps://.*\z)/]
> 
> Interesting. That implies it also accepts `https://` which doesn't make sense to me since I don't consider it an HTTP(S) URL.

Actually, you're correct. We shouldn't allow an empty value after ://

 I'll fix that with your suggestion.

It looks like the Stdlib:HTTPSUrl allows that for some reason?

2022-08-17 16:54 UTC, ekohl commented
> It looks like the Stdlib:HTTPSUrl allows that for some reason?

Possibly an oversight and nobody ran into problems because of it.

2022-08-17 17:33 UTC, canth1 commented
The spec tests are failing, but I can't figure out why?

Resource type not found: Apache::ModProxyProtocol

Not sure why it's giving me that error?

2022-08-17 20:46 UTC, ekohl commented
Because of https://github.com/puppetlabs/puppetlabs-apache/pull/2289#discussion_r948196017. You must name it according to the conventions so the loader finds it, so `types/mod_proxy_protocol.pp`.

2022-08-22 09:40 UTC, ekohl approved these changes
This looks good to me. @david22swan you requested changes, mind taking another look? Also, IMHO we should squash this on merge.

2022-08-22 09:44 UTC, david22swan approved these changes
LGTM

Everything look's good to me, only small comment is that the variables aren't aligned, but since there are only two of them it's not that big of a deal in my eyes.
Will go ahead with a squash merge.

2022-08-22 09:50 UTC, merged