fix mod_proxy_html on FreeBSD
puppetlabs/puppetlabs-apache pull request #2355
Opened 2022-12-11 22:10 UTC by fraenki

Previously trying to activate mod_proxy_html on FreeBSD resulted in the following error:

```
Error: /Stage[main]/Apache::Mod::Proxy_html/Apache::Mod[proxy_html]/Package[www/mod_proxy_html]/ensure: change from 'absent' to 'present' failed:
  Execution of '/usr/local/sbin/pkg install -qy www/mod_proxy_html' returned 1:
  pkg: No packages available to install matching 'www/mod_proxy_html' have been found in the repositories
```

The module files are already included in the base Apache port/package, the separate port was EOLed in 2018:
https://www.freshports.org/www/mod_proxy_html

2022-12-11 23:04 UTC, ekohl requested changes
spec test failures are related.

2022-12-11 23:27 UTC, fraenki commented
Fixed :)

2022-12-12 11:59 UTC, ekohl approved these changes
Thanks!

2022-12-12 14:02 UTC, david22swan approved these changes

2022-12-12 14:02 UTC, merged