(CONT-406) Fix for RHEL 7 compatibility
puppetlabs/puppetlabs-apache pull request #2362
Opened 2022-12-20 15:01 UTC by david22swan

A previous PR had updated the security_crs.comf.erb file to a more modern version, however this has rendered it incompatible with RHEL 7. This PR introduces and if to solve the issue.

Also includes a quick fix to remove legacy facts from a template file.

2022-12-20 23:28 UTC, ekohl requested changes
I wouldn't mind converting to EPP eventually, but we're not there today.

2022-12-20 23:28 UTC, ekohl commented on templates/mod/security.conf.erb
> +<%- if $facts['os']['family'] == 'Debian' -%>
This is ERB, not EPP

2022-12-21 09:57 UTC, david22swan commented on templates/mod/security.conf.erb
> +<%- if $facts['os']['family'] == 'Debian' -%>
crap, read the wrong guide

2022-12-21 14:05 UTC, GSPatton approved these changes
looks good to me

2022-12-21 14:40 UTC, merged