✨ Allow to set the verbosity of the debug
puppetlabs/puppetlabs-apache pull request #2523
Opened 2024-01-31 16:42 UTC by JGodin-C2C

## Summary
Allow to set the verbosity of the debug

2024-01-31 17:21 UTC, ekohl requested changes
I'm rather allergic to emojis in commit messages and would like to keep those out of the log. Can you drop it?

2024-01-31 17:21 UTC, ekohl commented on manifests/mod/security.pp
> +  String $debug_log_level                                      = '0',
Is this really a string and not an integer? https://www.feistyduck.com/library/modsecurity-handbook-free/online/ch04-logging.html suggests it should be
```suggestion
  Integer[0, 10] $debug_log_level                              = 0,
```

2024-02-01 16:47 UTC, ekohl submitted a review, later dismissed

2024-02-27 12:29 UTC, JGodin-C2C commented
hello ! what is missing here to see this merged in the main branch ?

2024-02-27 12:55 UTC, JGodin-C2C commented on manifests/mod/security.pp
> +  Integer[0, 10] $debug_log_level                              = 0,
Good catch ! you are right . I changed this to [0, 9] .

2024-02-27 12:58 UTC, bastelfreak commented
@JGodin-C2C please take a look at your git history. you did a merge instead of a merge. Please do a proper rebase, as @smortex suggested, to remove the merge commit.

2024-02-27 12:58 UTC, smortex submitted a review, later dismissed
LGTM, let's trigger another CI!

2024-02-27 13:06 UTC, JGodin-C2C commented
> @JGodin-C2C please take a look at your git history. you did a merge instead of a merge. Please do a proper rebase, as @smortex suggested, to remove the merge commit.

Yep, sorry, juggling with different remote is sometime hazardous.

Rebase should be correct now.

2024-02-27 13:20 UTC, smortex commented on manifests/mod/security.pp
> +  Integer[0, 10] $debug_log_level                              = 0,
Looks-like we are back to 10 :upside_down_face:

2024-02-27 13:24 UTC, JGodin-C2C commented on manifests/mod/security.pp
> +  Integer[0, 10] $debug_log_level                              = 0,
I am rather displeased by this error. 

I will blame the chair for this.

2024-02-27 13:28 UTC, smortex submitted a review, later dismissed
That feels good!

2024-02-27 13:52 UTC, JGodin-C2C commented
> That feels good!

Thanks for taking time to review my Merge Request even tho i stumbled on the carpet on repeated time

2024-02-27 14:51 UTC, JGodin-C2C commented
Sorry :( i pushed to the main branch again. my bad.

2024-03-05 07:55 UTC, JGodin-C2C commented
Hey @smortex i hope it's okay to query you in that way.

Any way to see this approved and merged  ?

2024-04-29 16:09 UTC, ekohl commented
There's still a merge commit in there.

2024-04-30 07:20 UTC, JGodin-C2C commented
okay, so, i took the tests from this PR (kudos to @zzacharo ): 
https://github.com/puppetlabs/puppetlabs-apache/pull/2524
and rebased.

2025-01-09 10:11 UTC, bastelfreak commented
Hi,
I'm currently holding off with reviews until https://www.puppet.com/blog/open-source-puppet-updates-2025 is sorted out.

2025-01-09 18:04 UTC, smortex approved these changes
Hi!  Same as @bastelfreak but in the meantime I merge PR which are approved regardless of an approval by some perforce employee because:
1. They have a track record of not being able to do this diligently;
2. They gave "trusted contributors" the GitHub permissions to do so.

2025-01-09 18:04 UTC, merged