Parametrize the SecDebugLogLevel
puppetlabs/puppetlabs-apache pull request #2524
Opened 2024-02-08 09:52 UTC by zzacharo

## Summary
At the moment the module hardcodes the mod_security debug level to 0 although it allows users to configure the debug log path. This PR introduces a new parameter called `debug_log_level` to be able to configure the `SecDebugLogLevel`.

## Checklist
- [x] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [ ] Manually verified. (For example `puppet apply`)

2024-02-08 09:52 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-apache?pullRequest=2524) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-apache?pullRequest=2524) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-apache?pullRequest=2524) it.</sub>

2024-02-08 10:30 UTC, traylenator commented
Re the CLA CERN IT has an agreement with Puppetlabs that we have signed the CLA.

2024-02-08 10:34 UTC, traylenator requested changes

2024-02-08 13:05 UTC, traylenator approved these changes

2024-02-23 07:50 UTC, zzacharo commented
@smortex any chance to integrate this soon-ish?

2024-02-26 20:22 UTC, smortex approved these changes
LGTM

2024-04-29 16:11 UTC, ekohl approved these changes
This looks like a more complete version of https://github.com/puppetlabs/puppetlabs-apache/pull/2523. However, I can't merge it because of the CLA check.

2026-08-31 19:32 UTC, jst-cyr commented
Hey @zzacharo , I'm reviewing old PRs and found this one from a while ago. Is this still an issue for you? If so, are you able to resolve conflicts with the latest from main?

2026-09-14 19:31 UTC, jst-cyr commented
I'll close this PR for now and we can always reoopen it in the future if a need arises.

2026-09-14 19:31 UTC, closed without merging