apache::params: Use correct PHP version on Ubuntu 24.04
puppetlabs/puppetlabs-apache pull request #2575
Opened 2024-10-23 16:37 UTC by flichtenheld

## Summary

Update PHP version list for Ubuntu 24.04 (noble)

## Additional Context
Straightforward.

## Related Issues (if any)

## Checklist
- [ ] 🟢 Spec tests.
- [ ] 🟢 Acceptance tests.
- [X] Manually verified. (For example `puppet apply`)

2024-10-23 16:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/puppetlabs/puppetlabs-apache?pullRequest=2575) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/puppetlabs/puppetlabs-apache?pullRequest=2575) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/puppetlabs/puppetlabs-apache?pullRequest=2575) it.</sub>

2024-10-23 17:50 UTC, ekohl requested changes
https://packages.ubuntu.com/noble/php confirms it's 8.3, but please fix the comment to match :)

2024-10-23 17:50 UTC, ekohl commented on manifests/params.pp
> +      '24.04' => '8.3', # Ubuntu Jammy
```suggestion
      '24.04' => '8.3', # Ubuntu Noble
```

2024-10-24 10:28 UTC, flichtenheld commented on manifests/params.pp
> +      '24.04' => '8.3', # Ubuntu Jammy
Fixed

2026-08-25 23:54 UTC, jst-cyr commented
Acceptance tests for Ubuntu 24.04 cannot be run with the changes made here (no Ubuntu 24 support added to metadata). Similar to results on #2619, will be closing this PR as insufficient for Ubuntu 24 support.

PR #2585 contains this change, along with others that are needed.

2026-08-25 23:54 UTC, closed without merging